import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f4f8', // Soft blue-gray for a premium backdrop
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 24,
    backgroundColor: '#ffffff', // White from your palette for crisp header
    borderRadius: 24,
    marginHorizontal: 16,
    marginTop: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 137, 216, 0.3)', // Subtle #0089d8 accent
  },
  logo: {
    width: width * 0.4,
    height: 100,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#0b0c0cff', // Your vibrant blue for logo pop
    shadowColor: '#0089d8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  dateTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1a2a44', // Dark blue-gray for sophistication
    marginVertical: 14,
    marginLeft: 8,
    fontFamily: 'Roboto', // Modern font (ensure available)
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 32,
    padding: 24,
    marginVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    borderLeftWidth: 6,
    borderLeftColor: '#0089d8', // Vibrant blue for visual pop
    overflow: 'hidden',
  },
  time: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0089d8',
    marginBottom: 12,
    letterSpacing: 0.8,
  },
  place: {
    fontSize: 16,
    color: '#333',
    marginBottom: 8,
    lineHeight: 26,
    fontWeight: '500',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 14,
    borderWidth: 2,
    borderColor: '#0089d8', // Blue border for consistency
    backgroundColor: '#f0f4f8',
  },
  avatarSmall: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: '#e0e0e0',
  },
  driverName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1a2a44',
    letterSpacing: 0.6,
  },
  detailText: {
    fontSize: 16,
    color: '#555',
    marginVertical: 4,
    lineHeight: 22,
    fontWeight: '400',
  },
  contactButton: {
    backgroundColor: '#0089d8',
    borderRadius: 32,
    paddingVertical: 14,
    paddingHorizontal: 24,
    marginTop: 14,
    alignItems: 'center',
    shadowColor: '#0089d8',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 5,
  },
  contactText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
    letterSpacing: 0.8,
  },
  subTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a2a44',
    marginBottom: 14,
    letterSpacing: 0.9,
  },
  passengerText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
    lineHeight: 26,
  },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 32,
    padding: 24,
    marginVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    borderTopWidth: 6,
    borderTopColor: '#0089d8', // Coral accent for prominence
    overflow: 'hidden',
  },
  dateRight: {
    fontSize: 16,
    color: '#555',
    textAlign: 'right',
    marginBottom: 12,
    fontWeight: '500',
  },
  summaryTime: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0089d8',
    marginBottom: 12,
    letterSpacing: 0.8,
  },
  summaryPlace: {
    fontSize: 16,
    color: '#333',
    marginBottom: 8,
    lineHeight: 26,
    fontWeight: '500',
  },
  driverSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 12,
  },
  price: {
    fontSize: 25,
    fontWeight: '600',
    color: '#1a1717ff', // Coral for standout pricing
    marginVertical: 14,
    textAlign: 'center',
    letterSpacing: 1,
  },
  bookButton: {
    backgroundColor: '#0089d8',
    borderRadius: 32,
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 16,
    shadowColor: '#0089d8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
    transform: [{ scale: 1 }],
  },
  bookText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
});