import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f0f7ff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0089d8ff',
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 32,
    padding: 16,
    elevation: 8,
    shadowColor: '#0089d8ff',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  headerCenter: {
    alignItems: 'center',
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 2,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#e6f4ff',
    fontWeight: '500',
  },
  helpButton: {
    padding: 8,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 20,
  },
  container: {
    flex: 1,
    backgroundColor: '#f0f7ff',
    paddingHorizontal: 10,
  },
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0089d8ff',
    marginHorizontal: 12,
    marginBottom: 16,
    borderRadius: 32,
    padding: 16,
    elevation: 8,
    shadowColor: '#0089d8ff',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  warningIconContainer: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  warningContent: {
    flex: 1,
    marginLeft: 12,
  },
  warningTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  warningText: {
    fontSize: 14,
    color: '#e6f4ff',
    marginTop: 2,
    fontWeight: '500',
  },
  updateButton: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    elevation: 4,
    shadowColor: '#000000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  updateButtonText: {
    color: '#000000', // Changed from #0089d8ff
    fontWeight: '700',
    fontSize: 14,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 16,
    backgroundColor: '#e6f4ff',
    marginHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000000', // Changed from #0089d8ff
    marginLeft: 12,
    flex: 1,
  },
  coverageCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginBottom: 12,
    marginHorizontal: 12,
    elevation: 6,
    shadowColor: '#0089d8ff',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    borderLeftWidth: 4,
    borderLeftColor: '#0089d8ff',
  },
  coverageCardGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
  },
  coverageIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0089d8ff',
  },
  coverageDetails: {
    flex: 1,
    marginLeft: 16,
  },
  coverageTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000000', // Changed from #0089d8ff
  },
  coverageDescription: {
    fontSize: 14,
    color: '#000000', // Changed from #4da6e0
    marginTop: 2,
    fontWeight: '500',
  },
  coverageAmount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000', // Changed from #0066b3
    marginTop: 4,
  },
  coverageAction: {
    padding: 8,
    backgroundColor: '#e6f4ff',
    borderRadius: 20,
  },
  legalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingHorizontal: 12,
  },
  legalCard: {
    flex: 0.48,
    backgroundColor: '#0c389fff',
    borderRadius: 16,
    elevation: 6,
    shadowColor: '#063e8eff',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  legalCardGradient: {
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 120,
    backgroundColor: '#0089d8ff',
  },
  legalCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    marginTop: 8,
    textAlign: 'center',
  },
  legalCardSubtitle: {
    fontSize: 14,
    color: '#e6f4ff',
    marginTop: 4,
    textAlign: 'center',
    fontWeight: '500',
  },
  importantNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#e6f4ff',
    marginHorizontal: 12,
    padding: 16,
    borderRadius: 16,
    elevation: 3,
    shadowColor: '#0089d8ff',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    borderLeftWidth: 4,
    borderLeftColor: '#0089d8ff',
  },
  legalNote: {
    fontSize: 14,
    color: '#000000', // Changed from #4da6e0
    marginLeft: 8,
    flex: 1,
    lineHeight: 18,
    fontWeight: '500',
  },
  claimButtonContainer: {
    marginTop: 20,
    marginBottom: 24,
  },
  claimButton: {
    backgroundColor: '#0089d8ff',
    marginHorizontal: 20,
    paddingVertical: 18,
    borderRadius: 25,
    alignItems: 'center',
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 20,
  },
  claimButtonText: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 16,
  },
  claimButtonTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  claimButtonSubtitle: {
    color: '#e6f4ff',
    fontSize: 14,
    fontWeight: '500',
    marginTop: 2,
  },
  footer: {
    alignItems: 'center',
    marginBottom: 20,
    backgroundColor: '#e6f4ff',
    marginHorizontal: 20,
    padding: 12,
    borderRadius: 12,
  },
  poweredBy: {
    fontSize: 14,
    color: '#000000', // Changed from #0089d8ff
    textAlign: 'center',
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 137, 216, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    width: '100%',
    maxHeight: '80%',
    elevation: 15,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    borderWidth: 2,
    borderColor: '#e6f4ff',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0089d8ff',
    padding: 20,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    flex: 1,
  },
  modalCloseButton: {
    padding: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 15,
  },
  modalBody: {
    padding: 20,
    backgroundColor: '#f0f7ff',
  },
  modalText: {
    fontSize: 14,
    color: '#000000', // Changed from #4da6e0
    lineHeight: 22,
    fontWeight: '500',
  },
  rideSectionDivider: {
    height: 2,
    backgroundColor: '#e6f4ff',
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 1,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 3,
  },
  timeText: {
    marginLeft: 8,
    color: '#000000', // Changed from #4da6e0
    fontSize: 14,
    fontWeight: '500',
  },
  carText: {
    marginLeft: 8,
    color: '#000000', // Changed from #0089d8ff
    fontSize: 14,
    fontWeight: '500',
  },
  ratingText: {
    marginLeft: 8,
    color: '#000000', // Changed from #0089d8ff
    fontSize: 14,
    fontWeight: '600',
  },
  costBreakdown: {
    alignItems: 'flex-end',
  },
  costDetail: {
    fontSize: 12,
    color: '#000000', // Changed from #4da6e0
    marginTop: 2,
    textAlign: 'right',
    fontWeight: '500',
  },
});

export default styles;