import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const StartNewClaimScreenCss = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f0f7ff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0089d8ff',
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 16,
    padding: 16,
    elevation: 8,
    shadowColor: '#0089d8ff',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    flex: 1,
    textAlign: 'center',
  },
  headerSpacer: {
    width: 24,
  },
  stepIndicator: {
    backgroundColor: '#ffffff',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e6f4ff',
  },
  progressBarContainer: {
    height: 6,
    backgroundColor: '#e6f4ff',
    borderRadius: 3,
    marginBottom: 8,
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#0089d8ff',
    borderRadius: 3,
  },
  stepText: {
    fontSize: 14,
    color: '#000000',
    fontWeight: '600',
    textAlign: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: '#f0f7ff',
    paddingHorizontal: 10,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingBottom: 120,
  },
  stepContainer: {
    padding: 20,
    paddingBottom: 20,
  },
  stepTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 8,
    textAlign: 'center',
  },
  stepSubtitle: {
    fontSize: 16,
    color: '#000000',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 22,
  },
  incidentTypesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  incidentTypeCard: {
    width: '48%',
    marginBottom: 16,
    borderRadius: 16,
    elevation: 6,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    borderLeftWidth: 4,
    borderLeftColor: '#0089d8ff',
    backgroundColor: '#ffffff', // Uniform white background for all cards
  },
  incidentTypeGradient: {
    flex: 1, // Ensure gradient covers entire card
    padding: 20,
    borderRadius: 16,
    alignItems: 'center',
    minHeight: 140,
    justifyContent: 'center',
    backgroundColor: '#ffffff', // Ensure Theft/Burglary matches other cards
  },
  selectedIncidentType: {
    elevation: 8,
    shadowOpacity: 0.25,
    backgroundColor: '#0089d8ff', // Full blue background for all selected cards
  },
  incidentTypeTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000000',
    marginTop: 12,
    textAlign: 'center',
  },
  incidentTypeDescription: {
    fontSize: 14,
    color: '#000000',
    marginTop: 6,
    textAlign: 'center',
    lineHeight: 18,
  },
  selectedText: {
    color: '#ffffff',
  },
  selectedDescriptionText: {
    color: '#e6f4ff',
    opacity: 0.8,
  },
  formGroup: {
    marginBottom: 24,
  },
  label: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e6f4ff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#000000',
    elevation: 1,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    marginBottom: 4,
  },
  textArea: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e6f4ff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#000000',
    minHeight: 120,
    textAlignVertical: 'top',
    elevation: 1,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  dateTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dateTimeInput: {
    flex: 0.48,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e6f4ff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#000000',
    elevation: 1,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  dateTimeButton: {
    flex: 0.48,
    backgroundColor: '#0089d8ff',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  dateTimeButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  photoSection: {
    marginTop: 16,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
  },
  photoItem: {
    width: (width - 60) / 3,
    height: (width - 60) / 3,
    marginRight: 8,
    marginBottom: 8,
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  addPhotoButton: {
    width: (width - 60) / 3,
    height: (width - 60) / 3,
    borderWidth: 2,
    borderColor: '#e6f4ff',
    borderStyle: 'dashed',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f0f7ff',
  },
  addPhotoText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '600',
  },
  tipsContainer: {
    backgroundColor: '#e6f4ff',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
  },
  tipsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 8,
  },
  tipText: {
    fontSize: 14,
    color: '#000000',
    marginBottom: 4,
    lineHeight: 18,
  },
  navigationContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: Platform.OS === 'ios' ? 34 : 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#e6f4ff',
    elevation: 8,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  previousButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#0089d8ff',
    backgroundColor: '#ffffff',
  },
  previousButtonText: {
    fontSize: 16,
    color: '#0089d8ff',
    fontWeight: '600',
    marginLeft: 8,
  },
  nextButton: {
    flex: 0.6,
    borderRadius: 25,
    elevation: 4,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  nextButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    backgroundColor: '#0089d8ff',
  },
  nextButtonText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
    marginRight: 8,
  },
  disabledButton: {
    opacity: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 137, 216, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  successModal: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    width: '100%',
    maxWidth: 400,
    elevation: 15,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    borderWidth: 2,
    borderColor: '#e6f4ff',
  },
  successHeader: {
    alignItems: 'center',
    padding: 30,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    backgroundColor: '#0089d8ff',
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    marginTop: 16,
  },
  successSubtitle: {
    fontSize: 14,
    color: '#e6f4ff',
    marginTop: 8,
    textAlign: 'center',
  },
  successBody: {
    padding: 24,
    backgroundColor: '#f0f7ff',
  },
  claimNumber: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 16,
    textAlign: 'center',
  },
  successMessage: {
    fontSize: 14,
    color: '#000000',
    lineHeight: 20,
    marginBottom: 20,
    textAlign: 'center',
  },
  nextSteps: {
    backgroundColor: '#e6f4ff',
    borderRadius: 12,
    padding: 16,
  },
  nextStepsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 12,
  },
  nextStepItem: {
    fontSize: 14,
    color: '#000000',
    lineHeight: 20,
    marginBottom: 8,
  },
  okButton: {
    marginTop: 24,
    borderRadius: 25,
    elevation: 4,
    shadowColor: '#0089d8ff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  okButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    backgroundColor: '#0089d8ff',
  },
  okButtonText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
  },
  // Responsive adjustments
  [`@media (max-width: ${width < 400 ? width : 400})`]: {
    incidentTypeCard: {
      width: '100%',
    },
    uploadButton: {
      flex: 1,
      marginHorizontal: 4,
    },
  },
  // Animation styles
  fadeIn: {
    opacity: 1,
  },
  slideIn: {
    transform: [{ translateX: 0 }],
  },
  // Form validation styles
  inputError: {
    borderColor: '#ff6b6b',
    backgroundColor: '#fff5f5',
  },
  errorText: {
    fontSize: 12,
    color: '#ff6b6b',
    marginTop: 4,
    marginLeft: 4,
  },
  requiredAsterisk: {
    color: '#ff6b6b',
  },
});