import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f4f8',
  },
  inner: {
    padding: 16,
    paddingBottom: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: 12,
    borderRadius: 18,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  logo: {
    width: width * 0.35,
    height: 70,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#0089d8',
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1a2a44',
    marginBottom: 12,
    marginLeft: 16,
    letterSpacing: 1,
    fontFamily: 'Roboto',
  },
  heading: {
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Roboto',
    color: '#1a2a44',
  },
  inputContainer: {
    marginBottom: 12,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  dateInputContainer: {
    marginBottom: 12,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  input: {
    backgroundColor: '#ffffff',
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    fontFamily: 'Roboto',
  },
  locationButton: {
    alignSelf: 'flex-end',
    marginTop: -8,
    marginBottom: 8,
  },
  locationLabel: {
    fontSize: 14,
    color: '#0089d8',
    fontWeight: '500',
    fontFamily: 'Roboto',
  },
  suggestionContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  suggestionItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  suggestionText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
    fontFamily: 'Roboto',
  },
  passengerContainer: {
    marginBottom: 12,
    padding: 12,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  passengerLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a2a44',
    marginBottom: 8,
    fontFamily: 'Roboto',
  },
  passengerControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  passengerButton: {
    backgroundColor: '#f0f4f8',
    borderRadius: 20,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  disabledButton: {
    backgroundColor: '#f0f0f0',
  },
  passengerCount: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1a2a44',
    minWidth: 40,
    textAlign: 'center',
    fontFamily: 'Roboto',
  },
  button: {
    marginTop: 16,
    paddingVertical: 8,
    borderRadius: 12,
    shadowColor: '#3d8ae1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
  },
  buttonLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    fontFamily: 'Roboto',
  },
});