import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    borderColor: '#0089d8',
    paddingHorizontal: 16, 
  },
  lottieBackground: {
    ...StyleSheet.absoluteFillObject,
    zIndex: -1,
  },
  inner: {
    flex: 1,
    justifyContent: 'center',
    width: '100%',
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 50,
    paddingHorizontal: 16,
    position: 'relative', // For positioning particles
  },
  logo: {
    width: width * 0.7,
    height: 270,
    borderRadius: 135, // Half of height for circular shape
    borderWidth: 2.5,
    borderColor: '#030303', // Initial color, animated in code
    shadowColor: '#0089d8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
 
  },
  glow: {
    position: 'absolute', 
    width: width * 0.7 + 20,
    height: 290,
    borderRadius: 145,
    backgroundColor: '#0089d8',
    opacity: 0.3,
    zIndex: -1,
  },
  particle: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#ff0000',
    zIndex: -1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 10,
    minHeight: height * 1.2,
  },
  formBox: {
    width: '90%', 
    padding: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 24,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 1.9,
    borderColor: 'rgba(0, 137, 216, 0.3)',
  },
  videoInsideForm: {
    width: '60%',
    height: 120,
    borderRadius: 24,
    marginTop: 50,
    marginBottom: 28,
    overflow: 'hidden',
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: '#0089d8',
  },
  title: {
    fontSize: 34,
    fontWeight: '900',
    color: '#212121',
    marginBottom: 36,
    textAlign: 'center',
    fontFamily: 'Roboto',
    textShadowColor: 'rgba(0, 137, 216, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    letterSpacing: 1.2,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 137, 216, 0.2)',
  },
  input: {
    flex: 1,
    backgroundColor: 'transparent',
    borderRadius: 10,
    color: '#212121',
    fontSize: 18,
    fontFamily: 'Roboto',
  },
  eyeIcon: {
    padding: 8,
  },
  button: {
    backgroundColor: '#0089d8',
    paddingVertical: 14,
    borderRadius: 40,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '900',
    fontFamily: 'Roboto',
    letterSpacing: 1.2,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  linkText: {
    color: '#0089d8',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 20,
    fontWeight: '700',
    fontFamily: 'Roboto',
    textShadowColor: 'rgba(0, 137, 216, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  forgotPasswordButton: {
    alignSelf: 'flex-end',
    marginBottom: 16,
    marginTop: -8,
  },
  forgotPasswordText: {
    color: '#0089d8',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Roboto',
    textShadowColor: 'rgba(0, 137, 216, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 1,
    borderColor: '#0089d8',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
  },
  checkboxChecked: {
    backgroundColor: '#0089d8',
  },
  rememberMeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  rememberMeText: {
    fontSize: 14,
    color: '#0089d8',
    fontFamily: 'Roboto',
    fontWeight: '600',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#212121',
    marginBottom: 16,
    fontFamily: 'Roboto',
  },
  modalSubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Roboto',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalButton: {
    flex: 1,
    marginHorizontal: 8,
  },
  modalCancelButton: {
    flex: 1,
    marginHorizontal: 8,
    backgroundColor: '#666',
  },
});

export default styles;