import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f4f8', // Soft blue-gray to match BookingStatusScreen
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 80, // Matches scroll padding
  },
  header: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 18,
    // Accent color
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1a2a44', // Dark blue-gray
    letterSpacing: 1,
    fontFamily: 'Roboto', // Ensure available or use system font
    textAlign: 'center',
  },
  referralSection: {
    backgroundColor: '#ffffff',
    padding: 24,
    borderRadius: 18,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  referralTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a2a44',
    marginBottom: 8,
    letterSpacing: 0.8,
    fontFamily: 'Roboto',
    textAlign: 'center',
  },
  referralSubText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#555',
    marginBottom: 12,
    textAlign: 'center',
  },
  referralContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 12,
  },
  referralCode: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a2a44',
    letterSpacing: 1.2,
    fontFamily: 'Roboto',
  },
  copyButton: {
    backgroundColor: '#0089d8', // Blue to match theme
    borderRadius: 25,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  copyButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 0.8,
    fontFamily: 'Roboto',
  },
  section: {
    backgroundColor: '#ffffff',
    padding: 24,
    borderRadius: 18,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    justifyContent: 'flex-start',
  },
  sectionIcon: {
    width: 40,
    height: 40,
    marginRight: 12,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a2a44',
    letterSpacing: 0.8,
    fontFamily: 'Roboto',
  },
  option: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  optionInner: {
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appLogo: {
    width: 40,
    height: 40,
    marginRight: 12,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  optionText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a2a44',
    letterSpacing: 0.8,
    fontFamily: 'Roboto',
  },
  subText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#555',
    marginTop: 4,
  },
  divider: {
    height: 1,
    backgroundColor: '#dcdcdc',
    marginVertical: 16,
  },
  footer: {
    backgroundColor: '#ffffff',
    paddingVertical: 20,
    borderRadius: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    marginBottom: 50,
  },
  footerText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#555',
    letterSpacing: 0.8,
    fontFamily: 'Roboto',
  },
});